version: '3.7'

services:
    app:
        build:
            context: .
            dockerfile: .docker/Dockerfile
        container_name: laravel-app
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www/html
        networks:
            - laravel-net
        depends_on:
            - database
    database:
        image: postgres
        container_name: laravel-db
        restart: unless-stopped
        ports:
            - "5433:5432"
        environment:
            POSTGRES_DB: laravel
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
        volumes:
            - ./database/dbdata:/var/lib/postgresql/data
            - ./database/pgsql/init:/docker-entrypoint-initdb.d
        networks:
            - laravel-net
networks:
    laravel-net:
        driver: bridge
